Controllers/AuthentificationController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjetFinal.Donnees;
using ProjetFinal.Models;
using System.Security.Claims;

// AuthentificationController sera responsable de la connexion et déconnexion des utilisateurs

namespace ProjetFinal.Controllers
{
    public class AuthentificationController : Controller
    {

        private readonly Bibliotheque _bibliotheque;


        public AuthentificationController(Bibliotheque bibliotheque)
        {
            _bibliotheque = bibliotheque;
        }

        // Methode responsable de l’affichage du formulaire de connexion
        public IActionResult Connexion()
        {

            return View();
        }


        [HttpPost, ValidateAntiForgeryToken]

        // Type complexe = type compose comme une classe (utilisateur est un type complexe =compose)
        // Type simple  = string, int..... (UrL et un type simple = string)
        public async Task<IActionResult> Connexion(Connexion formulaire, string? ReturnUrl)
        {
            if (!ModelState.IsValid) { return View(); }

            var user = await _bibliotheque.Utilisateurs.FromSql($@"
                SELECT * FROM [Utilisateurs]
                WHERE [Courriel] = {formulaire.Courriel}
                AND [MotDePasse] = HASHBYTES('SHA2_256',{formulaire.MotDePasse})
            ")
                .Include(v => v.Roles)
                .FirstOrDefaultAsync();

            if (user == null)
            {
                ModelState.AddModelError(string.Empty, "informations invalides");
                return View();
            }

            var claims = new List<Claim> {
                new Claim(ClaimTypes.NameIdentifier, user.ID.ToString())
            };

            user.Roles.ForEach(role =>
            {
                claims.Add(new Claim(ClaimTypes.Role, role.Nom));
            });


            await HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,  // Ici on dit quon va utiliser un cookie
                new ClaimsPrincipal(new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme)), //On  passe les informations
                new AuthenticationProperties { });

            //Response.Cookies.Append("Name", user.Nom + " " + user.Prenom);

            //Avec LocalRedirect on s'assure que si qqun allait modifier les info envoyés pour le formalaire dun URL vers un site externe LocalRedirect le blocarait   
            // Car localredirect verifie que l'url passé en parametre est un URL local
            return ReturnUrl != null ? LocalRedirect(ReturnUrl) : RedirectToAction(nameof(HomeController.Index), "Home");
        }

        [Authorize]
        public async Task<IActionResult> Déconnexion()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            return RedirectToAction(nameof(HomeController.Index), "Home");
        }

        public IActionResult Interdit()
        {
            return View();
        }
        

        


    }
}

Controllers/OuvrageController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjetFinal.Donnees;
using ProjetFinal.Models;
using System.Security.Claims;

namespace ProjetFinal.Controllers
{
    public class OuvrageController : Controller
    {
        private readonly Bibliotheque _bibliotheque;

        public OuvrageController(Bibliotheque bibliotheque)
        {
            _bibliotheque = bibliotheque;
        }



        public async Task<IActionResult> Index()
        {
            var ouvrage = await _bibliotheque.Ouvrages.ToListAsync();
            return View(ouvrage);
        }


        [Authorize(Roles = "Admin, User")]
        public async Task<IActionResult> Modification(int id)
        {
            var ouvrage = await _bibliotheque.Ouvrages.FindAsync(id);

            if (ouvrage != null)
            {
                return View(ouvrage);
            }

            return NotFound();
        }


        [Authorize(Roles = "Admin,User")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Modification(int id, Ouvrages formulaire)
        {
            if (!ModelState.IsValid)
            {
                return View(formulaire);
            }

            var ouvrage = await _bibliotheque.Ouvrages.FindAsync(id);

            if (ouvrage != null)
            {
                ouvrage.Titre = formulaire.Titre;
                ouvrage.Auteur = formulaire.Auteur;
                ouvrage.Exemplaires = formulaire.Exemplaires;

                await _bibliotheque.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            return NotFound();
        }


        public async Task<IActionResult> Ajouter(int id, int ouvrageId)
        {

            var utilisateur = await _bibliotheque.Utilisateurs.FindAsync(id);
            var ouvrage = await _bibliotheque.Ouvrages.FindAsync(ouvrageId);

            if (ouvrage == null || utilisateur == null)
            {
                return NotFound();
            }
            var nombreLimite = await _bibliotheque.Reservations.Include(v => v.Utilisateurs).Where(v => v.Utilisateurs.ID == id).ToListAsync();

            var nombre = nombreLimite.Count;

            if (nombre >= 3)
            {
               return RedirectToAction(nameof(Index));
                
            }
     

            var reserv = new Reservations { Ouvrage = ouvrage, Utilisateurs = utilisateur };

            await _bibliotheque.Reservations.AddAsync(reserv);
            await _bibliotheque.SaveChangesAsync();

            return View(nameof(Modification));
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Ajouter(Ouvrages donnees)
        {
            if (!ModelState.IsValid)
            {
                return View(nameof(Modification), donnees);
            }
            await _bibliotheque.Ouvrages.AddAsync(new Ouvrages()
            {
                Titre = donnees.Titre,
                Auteur = donnees.Auteur,
                Exemplaires = donnees.Exemplaires
            });
            await _bibliotheque.SaveChangesAsync();
            return RedirectToAction(nameof(Modification));          
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, User")]
        public async Task<IActionResult> Confirmation(int id)

        {
            var ouvrage = await _bibliotheque.Ouvrages.FindAsync(id);

            var utilisateur = await _bibliotheque.Utilisateurs
                    .Where(v => v.Courriel.Equals(HttpContext.User.FindFirstValue(ClaimTypes.Email)))
                    .FirstOrDefaultAsync();

            var nombreReserations = await _bibliotheque.Reservations
                .Where(v => v.Utilisateurs.Equals(utilisateur))
                .CountAsync();

            if (ouvrage != null && utilisateur != null)
            {
                if (nombreReserations < 3 && ouvrage.Exemplaires > 0)
                {
                    await _bibliotheque.Reservations.AddAsync(new Reservations { Utilisateurs = utilisateur, Ouvrage = ouvrage });

                    ouvrage.Exemplaires -= 1;

                    await _bibliotheque.SaveChangesAsync();

                    return View(ouvrage);
                }
            }

            return NotFound();
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> ConfirmationAdmin(int id)
        {
            var ouvrage = await _bibliotheque.Ouvrages.FindAsync(id);

            if (ouvrage != null)
            {
                return View(ouvrage);
            }

            return NotFound();
        }




        // [HttpPost]
        // [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Suppression(int id)
        {
            var ouvrage = await _bibliotheque.Ouvrages.FindAsync(id);

            if (ouvrage != null)
            {
                _bibliotheque.Ouvrages.Remove(ouvrage);

                await _bibliotheque.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            return NotFound();

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        
        public IActionResult Recherche(string titre, string auteur)
        {
            //List<Ouvrages> found = new();
             List<Ouvrages> found = _bibliotheque.Ouvrages.ToList();

            if (!string.IsNullOrEmpty(titre))
               
            {
                found = _bibliotheque.Ouvrages.Where(x => x.Titre.ToLower().Contains(titre.ToLower())).ToList();
            
            }

            if (!string.IsNullOrEmpty(auteur))

            {
                found = _bibliotheque.Ouvrages.Where(x => x.Auteur.ToLower().Contains(auteur.ToLower())).ToList();
            }


            return View(found);

        }

        public IActionResult ResReussi()
        {
            return View();
        }
    }
}

Controllers/ReservationController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjetFinal.Donnees;
using ProjetFinal.Models;
using System.Net;
using System.Security.Claims;

namespace ProjetFinal.Controllers
{
    public class ReservationController : Controller
    {

        private readonly Bibliotheque _bibliotheque;

        public ReservationController(Bibliotheque bibliotheque)
        {
            _bibliotheque = bibliotheque;
        }
        // Liste de toutes les ouvrages
        public async Task<IActionResult> Index()
        {

            var reservations = await _bibliotheque.Reservations.Include(v => v.Utilisateurs).Include(v => v.Ouvrage)
                .ToListAsync();


          
           return View(reservations);
        }

        public async Task<IActionResult> Confirmation(int id)
        {
            var reserv = await _bibliotheque.Reservations.FindAsync(id);
            if (reserv != null)
            {
                return View(reserv);
            }

            return NotFound();
        }

       
        public async Task<IActionResult> Suppression(int id)
        {
            var reserv = await _bibliotheque.Reservations
                .Include(v => v.Ouvrage)
                .Include(v => v.Utilisateurs)
                .Where(v => v.ID == id)
                .FirstAsync();

            if (reserv != null)
            {

                var ouvrage = await _bibliotheque.Ouvrages.FindAsync(reserv.Ouvrage.ID);
                var utilisateur = await _bibliotheque.Utilisateurs.FindAsync(reserv.Utilisateurs.ID);

                _bibliotheque.Reservations.Remove(reserv);

                ouvrage.Exemplaires += 1;
                utilisateur.Reservations.Remove(reserv);

                await _bibliotheque.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            return NotFound();
        }



        // [Authorize(Roles = "Admin,User")]
        [HttpGet("[action]/{id:int}/{userId:int}")]

        [Authorize(Roles = "Admin, User")]
        public async Task<IActionResult> Reserver(int id, int userId)

        {
            var ouvrage = await _bibliotheque.Ouvrages.FindAsync(id);

            var utilisateur = await _bibliotheque.Utilisateurs.FindAsync(userId);

            var nombreReserations = await _bibliotheque.Reservations
                .Where(v => v.Utilisateurs.Equals(utilisateur))
                .CountAsync();

            if (ouvrage != null && utilisateur != null)
            {
                if (nombreReserations < 3 && ouvrage.Exemplaires > 0)
                {
                    await _bibliotheque.Reservations.AddAsync(new Reservations { Utilisateurs = utilisateur, Ouvrage = ouvrage });

                    ouvrage.Exemplaires -= 1;

                    await _bibliotheque.SaveChangesAsync();

                    return View(ouvrage);
                }
            }

            return NotFound();
        }
       

    }
}

Views/Shared/_Layout.cshtml
@using System.Security.Claims
@using Microsoft.AspNetCore.Localization;
@{
    var connecte = Context.User.Identity!.IsAuthenticated;
   
    IRequestCultureFeature culture = Context.Features.Get<IRequestCultureFeature>()!;
    var chemin = Context.Request.Path;
}
@inject IViewLocalizer Localizer



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjetFinal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjetFinal.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProjetFinal</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ouvrage" asp-action="Index">Ouvrages</a>
                        </li>
                        
                        
                        <li class="nav-item">
                            @if (connecte)
                            {
                                <a class="nav-link text-dark" asp-area="" asp-controller="Reservation" asp-action="Index">Reservation</a>
                            }
                        </li>




                        <li class="nav-item">
                        @if (connecte)
                        {
                            <a class="nav-link text-dark"
                                asp-controller="Authentification"
                                asp-action="Déconnexion">Déconnexion</a>
                        }
                        else
                        {
                            <a class="nav-link text-dark"
                               asp-controller="Authentification"
                               asp-action="Connexion"
                               asp-route-ReturnUrl="@Context.Request.Path">Connexion</a>
                        }
                        </li>



                    </ul>
                    
                    @*await Component.InvokeAsync("Login")*@

                    <form asp-controller="Home" asp-action="Culture">
                        <select name="Culture"
                                asp-for="@culture.RequestCulture.Culture.Name"
                                class="form-select"
                                onchange="this.form.submit();">

                            <option value="en-CA">@Localizer["Anglais (Canada)"]</option>
                            <option value="fr-CA">@Localizer["Francais (Canada)"]</option>
                        </select>
                        <input type="hidden" asp-for="@chemin" />
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ProjetFinal - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>